name: GitHub Actions Example # nome do workspace

on:
  issues: # evento que aciona o workflow
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
